---
- name: Check prerequisites
  fail:
    msg: "You MUST provide a vault configuration through the variable vault_server_config_path"
  when: vault_server_config_path is not defined and vault_server_mode != 'development'

- name: Create vault user
  user:
    name: "{{vault_user}}"
    password: "{{vault_user_password}}"

- name: Create vault directory
  file:
    path: "{{vault_dir}}"
    state: directory
    owner: "{{vault_user}}"
    group: "{{vault_user}}"

- name: Check vault version
  shell: "vault --version 2>&1 | grep {{vault_version}}"
  failed_when: false
  changed_when: false
  register: vault_versions_match

- include: download.yml
  when: vault_versions_match.rc != 0

- name: Install unzip to unarchive vault
  apt:
    name: unzip
    state: present

- name: Unarchive vault archive
  unarchive:
    src: /tmp/vault-{{vault_version}}.zip
    dest: "{{vault_dir}}"
    copy: no
  when: vault_versions_match.rc != 0

- name: Make vault_user vault directory owner
  file:
    path: "{{vault_dir}}"
    state: directory
    owner: "{{vault_user}}"
    group: "{{vault_user}}"
    recurse: yes

- name: Adding vault command to user path
  file:
    src: "{{vault_dir}}/vault"
    dest: /usr/bin/vault
    state: link

- name: Create vault log directory
  file:
    path: "{{vault_server_log_dir}}"
    state: directory
    owner: "{{vault_user}}"
    group: "{{vault_user}}"
  when: vault_server
  register: vault_log_task

- include: service.yml
